### ISSUE TITLE
Parsing issue with space

### ISSUE THREAD

**Issue by we29758143** [mwilliamson/python-mammoth#102]
I found out there is a mismatch while parsing bullet point, here is an example:

> **My original document:**

![image](https://user-images.githubusercontent.com/47550645/113366585-a23f5800-9327-11eb-9a80-2c2f578789f2.png)

> **Parsing document**

![image](https://user-images.githubusercontent.com/47550645/113366503-62787080-9327-11eb-94b2-9b7eea37b290.png)

There is a space between each section and its related sentence. However, there is a missing space in "Section 4". Can you tell me where can I fix it?

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, as well as the expected and generated HTML (as text rather than images)?

**Comment by mwilliamson** [comment]
Closing since I don't think I can investigate without a document to look at.
