### ISSUE TITLE
Can you change image alt text when converting from docx?

### ISSUE THREAD

**Issue by mattl1598** [mwilliamson/python-mammoth#103]
I've written my own image converter function based on the example one in order to store the image in a database and display it with the right "src" but I can't find the right key for changing the alt text from the original file path that word stores.

I've tried "alt", "alt_text" and "title" to no avail. 

(question)

**Comment by mwilliamson** [comment]
At the moment, this isn't supported: the alt text will always be taken from the original document if it's available.

**Comment by mattl1598** [comment]
An update to this issue, the newest version of word automatically generates alt text with AI and uses line breaks which causes rendering issues with the resulting markdown. I'm working on a fix for my original issue and this new one currently.

**Comment by mwilliamson** [comment]
As of 1.5.0, you can override the alt text by adding an `"alt"` entry to the returned `dict`.
