### ISSUE TITLE
Cannot install mammoth==1.4.17 via docker

### ISSUE THREAD

**Issue by Avin-Techv** [mwilliamson/python-mammoth#107]
When trying to install mammoth via docker for a django project I get the errror

> ERROR: Cannot install mammoth==1.4.16 and mammoth==1.4.17 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested mammoth==1.4.17
>     The user requested mammoth==1.4.16
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
> ERROR: Service 'app' failed to build : The command '/bin/sh -c pip install -r /requirements.txt' returned a non-zero code: 1
>

**Comment by mwilliamson** [comment]
What does your requirements.txt file look like? It sounds like you're trying to install two different versions of Mammoth at the same time.

**Comment by Avin-Techv** [comment]
yes, it was the case thanks

**Comment by Avin-Techv** [comment]
yes, it was the case thanks
