### ISSUE TITLE
<i> instead of <em> tag

### ISSUE THREAD

**Issue by giuliovale** [mwilliamson/python-mammoth#11]
Hi any possibility to map italic text to `<i>` tag instead of `<em>` tag.
Thanks

**Comment by mwilliamson** [comment]
Not at the moment, however support for this could be added to style maps in the same way that, say, underlines are supported. Not sure sure when I'll get a chance to look at this, but feel free to take a look yourself if it takes your fancy.

**Comment by mwilliamson** [comment]
Style mappings for bold and italic runs are now supported as of 0.3.30.

**Comment by giuliovale** [comment]
Thanks
Il 25 feb 2016 8:16 PM, "Michael Williamson" <notifications@github.com> ha
scritto:
