### ISSUE TITLE
Mapping a paragraph style to multiple html elements (e.g., bold and italics)

### ISSUE THREAD

**Issue by deltamacht** [mwilliamson/python-mammoth#111]
I'm parsing a Word document with python-docx and inspecting the various styles that are present. I then want to take this information and build out a style_map for mammoth. However, I have styles which are both bold and italicized. I know how to map the style to either one of those two, but I do not know how to wrap paragraphs in both tags simultaneously. Is this possible with the style map, or do I need to create a custom mapping to a bold_italic style and then process that downstream?

**Comment by deltamacht** [comment]
Nevermind, figured it out. Thanks.

**Comment by wenestam** [comment]
Hello, I am currently also trying to understand this. Could you leave an example of mapping where you have 2 conditions required to be met? Eg: I would like Bold and Underlined text to be converted to "h2", how do I make the mapping to take into account both conditions?
