### ISSUE TITLE
installed with pip; mammoth not recognized

### ISSUE THREAD

**Issue by guzzijones** [mwilliamson/python-mammoth#12]
I followed the instructions at https://pypi.python.org/pypi/mammoth to install mammoth.  when I attempt to run it from the command line I get : mammoth not recognized.

I am not familiar with how to get this recognized.

**Comment by mwilliamson** [comment]
Are you trying to use Mammoth on the command line or as a library?

Could you post exactly what you're trying to run, and the error you get?

**Comment by guzzijones** [comment]
Command line.  It works fine as a library imported into a script. I am not 
familiar with what needs to be in place to run this package via command 
line. I did the pip install. O seem to be having a general issue with this 
package that may not be related to this specific package. Is there a 
documentation on line related to this general issue?

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by guzzijones** [comment]
I think this has to do with using Canopy as my python environment.
It seems to not be able to run anything in the user/scripts folder.
forget about this.

**Comment by guzzijones** [comment]
Turns out windows does not like any script in the ./Scripts folder that is not an .exe

```
C:\Python27\Scripts>mammoth
'mammoth' is not recognized as an internal or external command,
operable program or batch file.

C:\Python27\Scripts>python mammoth
usage: mammoth [-h] [--output-dir OUTPUT_DIR]
               [--output-format {markdown,html}] [--style-map STYLE_MAP]
               docx-path [output-path]
mammoth: error: too few arguments
```

**Comment by mwilliamson** [comment]
Glad you got it sorted.
