### ISSUE TITLE
bug: program crash if docx file has complicate content format

### ISSUE THREAD

**Issue by alexmaehon** [mwilliamson/python-mammoth#121]
When I run the code below, the program crash without even printing out the except content
I only wish it would not crash, even can not process the file, it will by pass the code

try:
    result = mammoth.convert_to_html(file_path)
    html = result.value # The generated HTML
except:
   print('convertion failed')

running on
Python 3.7.12
Ubuntu 18.04.5 LTS

[test2.docx](https://github.com/mwilliamson/python-mammoth/files/8167671/test2.docx)

**Comment by mwilliamson** [comment]
Could you post the full output when you try to run the conversion?

**Comment by alexmaehon** [comment]
I check my code thoroughly this time, it appears is not mammoth's problem. Sorry for the trouble and thank you for this wonderful tool~
