### ISSUE TITLE
some issue about x-wmf to png

### ISSUE THREAD

**Issue by jaja43439** [mwilliamson/python-mammoth#125]
Hello

**Comment by mwilliamson** [comment]
Could you post the actual errors you're getting when you try the code?

**Comment by jaja43439** [comment]
Method 1:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [19], in <cell line: 7>()
      7 with open(r'C:\Users\user\Desktop\a.docx', "rb") as fileobj:
      8     print(fileobj)
----> 9     result = mammoth.convert_to_html(fileobj, convert_image=convert_image)
     11 with open(r'C:\Users\user\Desktop\a.html', "w" , encoding='utf-8-sig') as html_file:
     12     html_file.write(result.value)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\__init__.py:12, in convert_to_html(*args, **kwargs)
     11 def convert_to_html(*args, **kwargs):
---> 12     return convert(*args, output_format="html", **kwargs)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\__init__.py:26, in convert(fileobj, transform_document, id_prefix, include_embedded_style_map, **kwargs)
     24 if include_embedded_style_map:
     25     kwargs["embedded_style_map"] = read_style_map(fileobj)
---> 26 return options.read_options(kwargs).bind(lambda convert_options:
     27     docx.read(fileobj).map(transform_document).bind(lambda document:
     28         conversion.convert_document_element_to_html(
     29             document,
     30             id_prefix=id_prefix,
     31             **convert_options
     32         )
     33     )
     34 )

File ~\anaconda3\envs\new\lib\site-packages\mammoth\results.py:15, in Result.bind(self, func)
     14 def bind(self, func):
---> 15     result = func(self.value)
     16     return Result(result.value, self.messages + result.messages)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\__init__.py:27, in convert.<locals>.<lambda>(convert_options)
     24 if include_embedded_style_map:
     25     kwargs["embedded_style_map"] = read_style_map(fileobj)
     26 return options.read_options(kwargs).bind(lambda convert_options:
---> 27     docx.read(fileobj).map(transform_document).bind(lambda document:
     28         conversion.convert_document_element_to_html(
     29             document,
     30             id_prefix=id_prefix,
     31             **convert_options
     32         )
     33     )
     34 )

File ~\anaconda3\envs\new\lib\site-packages\mammoth\results.py:15, in Result.bind(self, func)
     14 def bind(self, func):
---> 15     result = func(self.value)
     16     return Result(result.value, self.messages + result.messages)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\__init__.py:28, in convert.<locals>.<lambda>.<locals>.<lambda>(document)
     24 if include_embedded_style_map:
     25     kwargs["embedded_style_map"] = read_style_map(fileobj)
     26 return options.read_options(kwargs).bind(lambda convert_options:
     27     docx.read(fileobj).map(transform_document).bind(lambda document:
---> 28         conversion.convert_document_element_to_html(
     29             document,
     30             id_prefix=id_prefix,
     31             **convert_options
     32         )
     33     )
     34 )

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:49, in convert_document_element_to_html(element, style_map, convert_image, id_prefix, output_format, ignore_empty_paragraphs)
     39 converter = _DocumentConverter(
     40     messages=messages,
     41     style_map=style_map,
   (...)
     46     comments=comments,
     47 )
     48 context = _ConversionContext(is_table_header=False)
---> 49 nodes = converter.visit(element, context)
     51 writer = writers.writer(output_format)
     52 html.write(writer, html.collapse(html.strip_empty(nodes)))

File <string>:6, in visit(self, value, arg0)

File <string>:1, in _accept1(self, visitor, arg0)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:83, in _DocumentConverter.visit_document(self, document, context)
     82 def visit_document(self, document, context):
---> 83     nodes = self._visit_all(document.children, context)
     84     notes = [
     85         document.notes.resolve(reference)
     86         for reference in self._note_references
     87     ]
     88     notes_list = html.element("ol", {}, self._visit_all(notes, context))

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:307, in _DocumentConverter._visit_all(self, elements, context)
    306 def _visit_all(self, elements, context):
--> 307     return [
    308         html_node
    309         for element in elements
    310         for html_node in self.visit(element, context)
    311     ]

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:310, in <listcomp>(.0)
    306 def _visit_all(self, elements, context):
    307     return [
    308         html_node
    309         for element in elements
--> 310         for html_node in self.visit(element, context)
    311     ]

File <string>:6, in visit(self, value, arg0)

File <string>:1, in _accept1(self, visitor, arg0)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:106, in _DocumentConverter.visit_paragraph(self, paragraph, context)
    103         return [html.force_write] + content
    105 html_path = self._find_html_path_for_paragraph(paragraph)
--> 106 return html_path.wrap(children)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\html_paths.py:32, in HtmlPath.wrap(self, generate_nodes)
     31 def wrap(self, generate_nodes):
---> 32     nodes = generate_nodes()
     34     for element in reversed(self.elements):
     35         nodes = element.wrap_nodes(nodes)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:99, in _DocumentConverter.visit_paragraph.<locals>.children()
     98 def children():
---> 99     content = self._visit_all(paragraph.children, context)
    100     if self._ignore_empty_paragraphs:
    101         return content

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:307, in _DocumentConverter._visit_all(self, elements, context)
    306 def _visit_all(self, elements, context):
--> 307     return [
    308         html_node
    309         for element in elements
    310         for html_node in self.visit(element, context)
    311     ]

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:310, in <listcomp>(.0)
    306 def _visit_all(self, elements, context):
    307     return [
    308         html_node
    309         for element in elements
--> 310         for html_node in self.visit(element, context)
    311     ]

File <string>:6, in visit(self, value, arg0)

File <string>:1, in _accept1(self, visitor, arg0)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:133, in _DocumentConverter.visit_run(self, run, context)
    130 for path in paths:
    131     nodes = partial(path.wrap, nodes)
--> 133 return nodes()

File ~\anaconda3\envs\new\lib\site-packages\mammoth\html_paths.py:32, in HtmlPath.wrap(self, generate_nodes)
     31 def wrap(self, generate_nodes):
---> 32     nodes = generate_nodes()
     34     for element in reversed(self.elements):
     35         nodes = element.wrap_nodes(nodes)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:110, in _DocumentConverter.visit_run.<locals>.<lambda>()
    109 def visit_run(self, run, context):
--> 110     nodes = lambda: self._visit_all(run.children, context)
    111     paths = []
    112     if run.is_small_caps:

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:307, in _DocumentConverter._visit_all(self, elements, context)
    306 def _visit_all(self, elements, context):
--> 307     return [
    308         html_node
    309         for element in elements
    310         for html_node in self.visit(element, context)
    311     ]

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:310, in <listcomp>(.0)
    306 def _visit_all(self, elements, context):
    307     return [
    308         html_node
    309         for element in elements
--> 310         for html_node in self.visit(element, context)
    311     ]

File <string>:6, in visit(self, value, arg0)

File <string>:1, in _accept1(self, visitor, arg0)

File ~\anaconda3\envs\new\lib\site-packages\mammoth\conversion.py:77, in _DocumentConverter.visit_image(self, image, context)
     75 def visit_image(self, image, context):
     76     try:
---> 77         return self._convert_image(image)
     78     except InvalidFileReferenceError as error:
     79         self._messages.append(results.warning(str(error)))

Input In [19], in convert_image(image)
      2 def convert_image(image):
----> 3     image = libreoffice_wmf_conversion(image, post_process=imagemagick_trim)
      4     print(image)
      5     return mammoth.images.data_uri(image)

Input In [1], in libreoffice_wmf_conversion(image, post_process)
     47         shutil.copyfileobj(image_fileobj, input_fileobj)
     49 output_path = os.path.join(temporary_directory, "image.png")
---> 50 subprocess.check_call([
     51     "libreoffice",
     52     "--headless",
     53     "--convert-to",
     54     "png",
     55     input_path,
     56     "--outdir",
     57     temporary_directory,
     58 ])
     60 with io.open(output_path, "rb") as output_fileobj:
     61     output = output_fileobj.read()

File ~\anaconda3\envs\new\lib\subprocess.py:368, in check_call(*popenargs, **kwargs)
    358 def check_call(*popenargs, **kwargs):
    359     """Run command with arguments.  Wait for command to complete.  If
    360     the exit code was zero then return, otherwise raise
    361     CalledProcessError.  The CalledProcessError object will have the
   (...)
    366     check_call(["ls", "-l"])
    367     """
--> 368     retcode = call(*popenargs, **kwargs)
    369     if retcode:
    370         cmd = kwargs.get("args")

File ~\anaconda3\envs\new\lib\subprocess.py:349, in call(timeout, *popenargs, **kwargs)
    341 def call(*popenargs, timeout=None, **kwargs):
    342     """Run command with arguments.  Wait for command to complete or
    343     timeout, then return the returncode attribute.
    344 
   (...)
    347     retcode = call(["ls", "-l"])
    348     """
--> 349     with Popen(*popenargs, **kwargs) as p:
    350         try:
    351             return p.wait(timeout=timeout)

File ~\anaconda3\envs\new\lib\subprocess.py:951, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    947         if self.text_mode:
    948             self.stderr = io.TextIOWrapper(self.stderr,
    949                     encoding=encoding, errors=errors)
--> 951     self._execute_child(args, executable, preexec_fn, close_fds,
    952                         pass_fds, cwd, env,
    953                         startupinfo, creationflags, shell,
    954                         p2cread, p2cwrite,
    955                         c2pread, c2pwrite,
    956                         errread, errwrite,
    957                         restore_signals,
    958                         gid, gids, uid, umask,
    959                         start_new_session)
    960 except:
    961     # Cleanup if the child failed starting.
    962     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File ~\anaconda3\envs\new\lib\subprocess.py:1420, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
   1418 # Start the process
   1419 try:
-> 1420     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1421                              # no special security
   1422                              None, None,
   1423                              int(not close_fds),
   1424                              creationflags,
   1425                              env,
   1426                              cwd,
   1427                              startupinfo)
   1428 finally:
   1429     # Child is launched. Close the parent's copy of those pipe
   1430     # handles that only the child should have open.  You need
   (...)
   1433     # pipe will not close when the child process exits and the
   1434     # ReadFile will hang.
   1435     self._close_pipe_fds(p2cread, p2cwrite,
   1436                          c2pread, c2pwrite,
   1437                          errread, errwrite)

FileNotFoundError: [WinError 2] The system cannot find the file specified。

**Comment by jaja43439** [comment]
I don't understand why the example code for libreoffice_wmf_conversion() didn't work

In Method 2 the libreoffice_wmf_conversion() parameter is confused me

**Comment by mwilliamson** [comment]
It looks to me as though the `libreoffice` executable can't be found. For that code to work, `libreoffice` will need to be on the path.

**Comment by jaja43439** [comment]
ok, but how can I know the original image position after covert

**Comment by mwilliamson** [comment]
I'm closing the issue since I don't think there's anything else I can do to help.
