### ISSUE TITLE
Q: how to match  "run style"?

### ISSUE THREAD

**Issue by zopyx** [mwilliamson/python-mammoth#128]
I have a DOCX with custom styles. However, I don't know how to map/match a "run style" in my styles mapping file

```
Unrecognised run style: Literaturverweis (Style ID: Literaturverweis)
Unrecognised run style: TherapieVergleich (Style ID: TherapieVergleich)
Unrecognised run style: Legendenzeichen Pfeil Blau (Style ID: LegendenzeichenPfeilBlau)
Unrecognised run style: Legendenzeichen Pfeil Gelb (Style ID: LegendenzeichenPfeilGelb)

```

**Comment by mwilliamson** [comment]
If, for instance, you wanted to map Literaturverweis to `span.literaturverweis`:

```
r[style-name='Literaturverweis'] => span.literaturverweis
```

**Comment by zopyx** [comment]
Thanks, problem solved. This information is missing in the docs.

**Comment by mwilliamson** [comment]
I believe it's covered under the section "Document element matchers": https://github.com/mwilliamson/python-mammoth#document-element-matchers
