### ISSUE TITLE
Grouping of elements?

### ISSUE THREAD

**Issue by zopyx** [mwilliamson/python-mammoth#129]
We have some documents with address lists where each entity of an address has its own style `AuthorAddress`, `AuthorName`, `AuthorFax` etc.

<img width="394" alt="Bildschirm­foto 2023-01-21 um 09 39 37" src="https://user-images.githubusercontent.com/594239/213859304-984e2c7a-63e0-40de-945d-3443cb4a85aa.png">

They are properly converted into 

```
<div class="authorname">...</div>
<div class="authoraddress">...</div>
<div class="authorfax">...</div>
<div class="authorname">...</div>
<div class="authoraddress">...</div>
<div class="authorfax">...</div>
```

All fine...is it possible to group all elements into an outer container like

```
<div class="author">
  <div class="authorname">...</div>
  <div class="authoraddress">...</div> 
  <div class="authorfax">...</div>
</div>
<div class="author">
  <div class="authorname">...</div>
  <div class="authoraddress">...</div> 
  <div class="authorfax">...</div>
</div>
```

**Comment by mwilliamson** [comment]
You'd probably want something like:

```
p[style-name='Author Name'] => div.author:fresh > div.authorname:fresh
p[style-name='Author Address'] => div.author > div.authoraddress:fresh
p[style-name='Author Address'] => div.author > div.authorfax:fresh
```

**Comment by zopyx** [comment]
Thank you! You saved my day!
