### ISSUE TITLE
Bookmarks in documents - propose they are span tags instead of anchors

### ISSUE THREAD

**Issue by bmo** [mwilliamson/python-mammoth#13]
If I have a simple docx with a link to a bookmark also inside that document, in word, clicking on the link goes to the text in the document.

Upon conversion, the location of the bookmark in the document is converted to another anchor tag, and the explicit link to the bookmark is the same tag. It doesn't have the same semantics as the original document. Was this intentional?

I propose that the actual bookmark itself is converted to a `span` tag, with an attribute of "data-mammoth-style":"bookmark" attached so that these elements can be found effectively if necessary. In the converted HTML, clicking on the link will go to the location of the span tag, like the original document.

**Comment by mwilliamson** [comment]
I'm not sure I follow the behaviour you're currently seeing. Do you have an example of a document, with the actual and expected HTML output?

When I try converting a document with a bookmark, the location of the bookmark has an empty anchor element with an ID (say, `introduction`), and the link to that bookmark is an anchor with a matching `href` attribute (say, `#introduction`), which replicates the original behaviour of the document.

**Comment by bmo** [comment]
Thanks for your reply; it appears that it's NOT a python-mammoth issue, but an issue with some of the other tools in a process not liking an href-less link (in this case, an old version of CKeditor). FYI, in the case with the particular version of this editor, pasting in the HTML source, then viewing it, removes the href links from the document. Ugh.
