### ISSUE TITLE
Keeping font sizes when converting DOCX to HTML using mammoth

### ISSUE THREAD

**Issue by phantom153** [mwilliamson/python-mammoth#135]
I have the following code that converts DOCX to HTML:

```
style_map = """
            u => u
        """
f = open(file + ".docx", 'rb')
b = open(file + '.html', 'wb')
document = mammoth.convert_to_html(f, style_map=style_map)
html = document.value
b.write(html.encode('utf8'))
f.close()
b.close()
```

The output looks good, however in the HTML all font sizes are the same whereas in the DOCX there are some bigger and smaller fonts. How can I save to HTML keeping the relative sizes of the font?

**Comment by mwilliamson** [comment]
Mammoth intentionally doesn't copy the exact formatting of the document. The idea is to instead apply appropriate paragraph and run styles, and to map those to the relevant HTML elements and CSS classes.

**Comment by phantom153** [comment]
Thanks. Isn't it possible to copy the relative sizes, e.g. big compared to small fonts?
If not, is there any other way to do that?

**Comment by mwilliamson** [comment]
You can use a document transform to map specific font sizes to document styles, and then use a style mapping to map document styles to the right HTML, but if you're just looking to directly the font sizes, then Mammoth isn't the right tool for the job.

**Comment by phantom153** [comment]
And also - Thank you for a great Python package!!!

**Comment by mwilliamson** [comment]
> Problem is, how do I know which words are bigger than others in order to apply the mapping?

It sounds like you'd want to do a first pass over the entire document to gather what the various font sizes are so you know their relative sizes. Having said that, it does sound like you're trying to do something that Mammoth isn't designed for.

**Comment by phantom153** [comment]
Thanks!

**Comment by phantom153** [comment]
Sorry for "reopening" - in the attached example you see that it did not keep the font sizes. 
Do you know what is the difference between the DOCXs?
[NocturnoENG.zip](https://github.com/mwilliamson/python-mammoth/files/11728007/NocturnoENG.zip)
