### ISSUE TITLE
mammoth.convert_to_markdown(fileobj, **kwargs): doesn't convert tables

### ISSUE THREAD

**Issue by junxu-ai** [mwilliamson/python-mammoth#137]
It seems that the coversion to markdown is not fully impletmented. the code shows that it calls the html function. 

Currently, i use mammoth to convert docx into html first, and then markdownify to convert the html to markdown. 

If you're reporting a bug or requesting a feature, please include:
* a minimal example document
[temp.docx](https://github.com/mwilliamson/python-mammoth/files/12407389/temp.docx)

* the markdown output that you'd expect
|  |  |  |  |  |
| --- | --- | --- | --- | --- |
|  | **C1** | **C2** | **C3** | **C4** |
| 2018 | 2 | 100 | B4 |
| 2019 | 230 | 5 |  |  |
| 2020 | 3 | 12.0 |  |  |
| 2021 | 4 | 5 | 253 |  |
| 2022 | 5 | 5 |  | 41 |
| Total  | 244 |  |  |  |

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the version of Python: 3.10
* the operating system and version:  Ubuntu
Thanks.

**Comment by mwilliamson** [comment]
Markdown support is deprecated, and converting first to HTML and then using something else to convert that HTML to Markdown (as you're already doing) is what's recommended.

**Comment by junxu-ai** [comment]
Thanks @mwilliamson. 

i'm just wondering if the additional step would introduce more format errors.

**Comment by eigen2017** [comment]
> Markdown support is deprecated, and converting first to HTML and then using something else to convert that HTML to Markdown (as you're already doing) is what's recommended.

yes html2text would work
