### ISSUE TITLE
Q: Is it possible to set a ordered-list/unordered-list with the style ID

### ISSUE THREAD

**Issue by softdev1029** [mwilliamson/python-mammoth#138]
I saw mammoth can specify the paragraph with the style ID.
```
p.Heading1 => h1.heading1:fresh
```
Is this correct?

Anyway, I have to specify the numbering too. I saw the default style map of mammoth and saw the numbering related line.
```
p:unordered-list(1) => ul > li:fresh
```

Now can I set the following and does it work?
```
p.Heading1:unordered-list(1) => h1.heading1 > ul > li:fresh

or

p.Heading1:unordered-list(1) => h1.heading1 > ul.heading1 > li:fresh
```

**Comment by mwilliamson** [comment]
I believe what you've written should work, but please feel free to open another issue if it doesn't.
