### ISSUE TITLE
[Enhancement Request] Including Outline Numbered

### ISSUE THREAD

**Issue by kmb232** [mwilliamson/python-mammoth#14]
Hey, great package, I can't tell you how much it's helped me out.
The dream document I'd love to be able to convert is in a massive outline format. Just wondering if you looked at Word's Numbered Outline layout as a possibility, or if it would be impossible. Or maybe there's a way to do it in the code, as is? Thanks!

**Comment by mwilliamson** [comment]
Thanks for the kind words. Do you mean that you want the HTML to end up looking like the document when viewed in the numbered outline layout? I'm not sure when I'll get a chance to look at it, but if you provide a small example document and the expected HTML output, then that'll help me make sure I'm looking at the right thing if I do get a chance.

**Comment by kmb232** [comment]
Thanks! I figured out the problem with it - the document I'm working with isn't a numbered outline by the Word definition, it's all custom formatting done by the author. Once I figured that out everything made more sense. The whole thing is just one giant mess of custom formats & styles. Can't tell you how much fun it is to deal with.

**Comment by mwilliamson** [comment]
Ah, in that case, can this issue be closed, or is there still something that would be helpful to Mammoth to implement?

**Comment by kmb232** [comment]
Nope, that's it, thanks!
