### ISSUE TITLE
Could I ask for a little change?

### ISSUE THREAD

**Issue by JacoboFeijoo** [mwilliamson/python-mammoth#140]
Hi,

First, congrats. This tool is quite comfortable.

Second, I would ask for a change. If I write italics in Word, this plugin translate it as &lt;em&gt; but I need an &lt;i&gt; 
I have the same problem with &lt;strong&gt; for bolds (I need a &lt;b&gt;). In professional edition of books (paper vs. digital) the difference is quite important.

Thanks in advance :o)

**Comment by mwilliamson** [comment]
Hello! The conversion of italics and bold can be controlled using style maps, as described in the docs: https://github.com/mwilliamson/python-mammoth#bold

**Comment by JacoboFeijoo** [comment]
> Hello! The conversion of italics and bold can be controlled using style maps, as described in the docs: https://github.com/mwilliamson/python-mammoth#bold

Clear! Thanks a lot :o)
