### ISSUE TITLE
Unordered list in paragraph with custom style including numbering cannot be retrieved properly ?

### ISSUE THREAD

**Issue by yldoctrine** [mwilliamson/python-mammoth#141]
Hello, thanks for your work !

I have an issue with a docx that comes with a custom style that includes some numbering rules.
In the docx there are some paragraphs with this style that contains some unordered lists. When I try to convert to html, the unordered list gets merged into the ordered list of the paragraph

I use the following style_map

> p:unordered-list(1) => ul > li:fresh
> p:ordered-list(1) => ol > li:fresh

Here are some example files to reproduce the issue
[ordered_list.docx](https://github.com/mwilliamson/python-mammoth/files/14536361/ordered_list.docx)
[ordered_list.txt](https://github.com/mwilliamson/python-mammoth/files/14536404/ordered_list.txt)
[expected_ordered_list.txt](https://github.com/mwilliamson/python-mammoth/files/14536406/expected_ordered_list.txt)

Inside the docx, in the numbering.xml I found the following which I think explains the problem

> <w:abstractNum w:abstractNumId="0" w15:restartNumberingAfterBreak="0">
>         <w:nsid w:val="3DCB54D7"/>
>         <w:multiLevelType w:val="hybridMultilevel"/>
>         <w:tmpl w:val="E616680A"/>
>         <w:lvl w:ilvl="0" w:tplc="C1C8AFB8">                          <--- This seems to be the problem
>             <w:start w:val="1"/>
>             <w:numFmt w:val="decimal"/>
>             <w:pStyle w:val="Customnumberedtext"/>               <--- this as well

Then in the library's code we end up here, applying the "level" of the style and loose the list in the document
 https://github.com/mwilliamson/python-mammoth/blob/master/mammoth/docx/body_xml.py#L242

I'm not sure on how to fix this, thanks for your insight on this issue

Running on Python 3.10 on MacOS Sonoma 14.3.1

**Comment by mwilliamson** [comment]
Hmm, it's probably the case that the precedence is the wrong way round: numbering properties applied directly to a paragraph should supersede those applied to the paragraph style.

**Comment by mwilliamson** [comment]
This should now be fixed in 1.7.1.
