### ISSUE TITLE
Not for Windows

### ISSUE THREAD

**Issue by ianchanning** [mwilliamson/python-mammoth#15]
I assume that mammoth is not available for Windows. Pip happily installs it, but it creates an executable in the Scripts directory which doesn't have a `.exe` file extension and appears to be quite clearly not any kind of Windows executable.

If it isn't could you add in a System requirements section to your readme?

**Comment by mwilliamson** [comment]
The package should work fine on Windows so far as I know since it just uses plain Python modules. I don't have Python on Windows to check, but I believe the behaviour on Windows is to install the scripts as Python files that can be run by the Python interpreter. I suppose a `.cmd` file could also be added to add support for running the file without having to explicitly invoke Python, but I can't test that at the moment.

**Comment by mwilliamson** [comment]
See, for instance, #12.

**Comment by mwilliamson** [comment]
Oh, apparently setuptools has better Windows support by using `entry_points` instead of `scripts`. I'll change that if I get a chance, but in the meantime, explicitly using the Python interpreter should work fine.

**Comment by mwilliamson** [comment]
Should be fixed in 1.0.1, let me know if not.

**Comment by ianchanning** [comment]
Thanks for looking into this. 

Yep #12 will solve my problem. However I think this means that I always have to pass the entire directory path into the command line:

```
C:\Users\Ian>python C:\ProgramData\chocolatey\lib\python3\tools\Scripts\mammoth
usage: mammoth [-h] [--output-dir OUTPUT_DIR]
               [--output-format {markdown,html}] [--style-map STYLE_MAP]
               docx-path [output-path]
mammoth: error: the following arguments are required: docx-path
```

I'm not quite sure what you mean by `entry_points`, I don't have that directory in my installation. 

My confusion was based on that everything else that i'd installed via pip had created an exe in the scripts directory, so I'd assumed that was the standard output when installing via pip:

![2016-04-20 09_23_29-photos](https://cloud.githubusercontent.com/assets/233318/14666647/1f9e1edc-06db-11e6-9ff9-1161494ca5e1.png)

**Comment by mwilliamson** [comment]
The latest version of mammoth (1.0.1) should now install an exe on
Windows, so let me know if not (unless you mean you've already
installed that version and it's still not working?). The reference to
`entry_points` was describing how arguments are passed to setuptools in
`setup.py` to make this work, so no need to worry about it.

**Comment by ianchanning** [comment]
Great, thanks! 
I've upgraded to v1.0.1 and it creates an exe file in the scripts directory  and so I can run mammoth independently.

![2016-04-20 11_21_59-search](https://cloud.githubusercontent.com/assets/233318/14669679/2ead17d4-06ea-11e6-9c93-08e039cb2727.png)
