### ISSUE TITLE
Custom List Styles

### ISSUE THREAD

**Issue by kmb232** [mwilliamson/python-mammoth#16]
Hi, I have another question. What's the best way to get different numbering styles in lists? Several lists in the documents I'm working with are using letters or Roman numerals, but it looks like the only options the code understands are numbered or not. Thanks so much for the help!

**Comment by mwilliamson** [comment]
Do you mean you want to change the style of all lists, or just selected lists? If the former, then applying some CSS to the output should do what you want. If the latter, then you can use style maps to map certain paragraph styles to particular classes in the HTML. For instance:

    p[style-name='Step Bullet'] => ul.step > li:fresh

will turn any Word paragraph that has the style named "Step Bullet" into an HTML `li` within a `ul` with the `step` class, which can then be styled as you like with CSS.
