### ISSUE TITLE
Getting BadZipFile issue

### ISSUE THREAD

**Issue by vipratiwari** [mwilliamson/python-mammoth#28]
Hey,
Trying to implement mammoth module but getting 
zipfile.BadZipFile: File is not a zip file

**Comment by mwilliamson** [comment]
I'll need some more information to be able to help:
* Could you post the code you're using?
* Can you successfully open the document as a zip file using another zip archive tool?
* Do any documents work? What happens if you try a blank document from Word?
* Could you provide an example document?

**Comment by vipratiwari** [comment]
Sure,
====================================================
import mammoth

with open("/home/vipra/Vipra/trotor/testfile.docx", "rb") as docx_file:
    result = mammoth.convert_to_html(docx_file)
    html = result.value # The generated HTML
    messages = result.messages # Any messages, such as warnings during conversion

with open("mammothhtml.html", "w") as ht:
    ht.write(message)
=====================================================================
This is the code 
I am not using zip file, this is normal text file
All other processing on document is working fine.
[testfile.docx](https://github.com/mwilliamson/python-mammoth/files/853941/testfile.docx)

I am using python 3.5.2

**Comment by mwilliamson** [comment]
And that's a Word document that's been created by Microsoft Word? Word documents are normally zip files, which is why Mammoth can't parse it. Given that the file doesn't seem to be XML, it's unlikely that support will be added to read that format.

**Comment by vipratiwari** [comment]
Hi,
But this is what Mammoth doc says 
 - "Mammoth is designed to convert .docx documents, such as those created by Microsoft Word, and convert them to HTML. "

**Comment by mwilliamson** [comment]
Could you clarify how your document was created? As I say, that's not
the format I'd expect for a Word document: they're normally zip files
containing XML (among other things).

**Comment by vipratiwari** [comment]
You are write, the issue was with file.
Thanks Willlamson.
