### ISSUE TITLE
Error in image converting

### ISSUE THREAD

**Issue by jwillmer** [mwilliamson/python-mammoth#3]
**Output** 
 `File "C:\Python34\lib\site-packages\mammoth\images.py", line 3, in convert_image attributes = func(image).copy()`
   `File "C:\Python34\lib\site-packages\mammoth\conversion.py", line 154, in _convert_image with image.open() as image_bytes:`
   `File "C:\Python34\lib\site-packages\mammoth\docx\document_xml.py", line 227, in open_image image_file = docx_file.open(image_path)`
  `File "C:\Python34\lib\zipfile.py", line 1148, in open zinfo = self.getinfo(name)`
  `File "C:\Python34\lib\zipfile.py", line 1084, in getinfo 'There is no item named %r in the archive' % name)`
 `KeyError: "There is no item named 'word\\\\media/image1.jpg' in the archive"`

**Testfile**
[Testcontent.docx (Dropbox)](https://www.dropbox.com/s/2hygo2fzim4o34p/Testcontent.docx?dl=0)

**Comment by mwilliamson** [comment]
Ah, I'm guessing you're on Windpws? This is probably because I'm incorrectly using `os.path.join` somewhere, whereas I should just be using forward slashes.

**Comment by mwilliamson** [comment]
I've just uploaded `0.3.13` to PyPI. Does it help?

**Comment by jwillmer** [comment]
**Fix is working** (on Windows).

But I needed to rename README.md to README in order to install/upgrade mammoth again. Can't tell if your modifications are guilty. I hadn't this complications at the last installation (this morning).  

`C:\WINDOWS\system32>pip install C:\Users\me\Desktop\python-mammoth-master`

`Processing c:\users\me\desktop\python-mammoth-master`
    `Complete output from command python setup.py egg_info:`
    `Traceback (most recent call last):`
      `File "<string>", line 20, in <module>`
      `File "C:\Users\me\AppData\Local\Temp\pip-k0vxi91r-build\setup.py", line 23, in <module> long_description=read("README"),`
      `File "C:\Users\me\AppData\Local\Temp\pip-k0vxi91r-build\setup.py", line 8, in read return open(os.path.join(os.path.dirname(__file__), fname)).read()`
    `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\me\\AppData\\Local\\Temp\\pip-k0vxi91r-build\\README'`

   ` ----------------------------------------`
    `Command "python setup.py egg_info" failed with error code 1 in C:\Users\me\AppData\Local\Temp\pip-k0vxi91r-build`

**Comment by jwillmer** [comment]
For completenes the stacktrace from the [Testcontent.docx (Dropbox)](https://www.dropbox.com/s/2hygo2fzim4o34p/Testcontent.docx?dl=0) after the fix:

`C:\WINDOWS\system32>python C:\Users\me\Desktop\python-mammoth-master\scripts\mammoth C:\Users\me\Desktop\Testcontent.docx C:\Users\me\Desktop\output.html`
`Unsupported break type: page`
`Unsupported break type: page`
`An unrecognised element was ignored: w:fldChar`
`An unrecognised element was ignored: w:instrText`
`An unrecognised element was ignored: w:fldChar`
`An unrecognised element was ignored: w:fldChar`
`Unrecognised run style: Title Char (Style ID: TitleChar)`
`Unrecognised paragraph style: heading 5 (Style ID: Heading5)`
`Unrecognised run style: apple-converted-space (Style ID: apple-converted-space)`
`Unrecognised run style: Hyperlink (Style ID: Hyperlink)`

**Comment by mwilliamson** [comment]
> But I needed to rename README.md to README in order to install/upgrade mammoth again. Can't tell if your modifications are guilty.

Was that installing from git or from PyPI? `README` is generated from `README.md` so you can't install the project directly from git, but it should work without issue from PyPI.

**Comment by jwillmer** [comment]
I used this command in the CMD:
`C:\WINDOWS\system32>pip install C:\Users\me\Desktop\python-mammoth-master`

**Comment by mwilliamson-firefly** [comment]
What's `C:\Users\me\Desktop\python-mammoth-master`? A clone from GitHub?

**Comment by mwilliamson** [comment]
What's `C:\Users\me\Desktop\python-mammoth-master`? A clone from GitHub?

**Comment by jwillmer** [comment]
yes

**Comment by mwilliamson** [comment]
Ah, okay, then that's known behaviour (albeit not particularly desireable). Thanks!
