### ISSUE TITLE
Some images don't come through, with no resulting img link

### ISSUE THREAD

**Issue by dividor** [mwilliamson/python-mammoth#31]
We are parsing hundreds of documents and Mammoth is really great, thanks!

One thing though, is that we have a lot of cases where the original word document has a '.wmf' image, but Mammoth doesn't detect it. There is no HTML link to the image in the generated results and the image isn't written to file by the image conversion function (or inline if this function is deactivated). 

If I unzip the word file, the image files are there as '.wmf'.

- Is there a way to have these images handled?
- Where in the Mammoth code is the check for image types please?

thanks a lot!

**Comment by mwilliamson** [comment]
If you could provide an example document, that would be helpful.

> * Where in the Mammoth code is the check for image types please?

Mammoth doesn't check for image types: it just includes whatever it finds as-is.

(That's not entirely true: Mammoth has a check for certain image types, but only to choose whether or not to emit a warning: https://github.com/mwilliamson/python-mammoth/blob/09ccf2bdc28da0ef5727848059872f995f9b30f4/mammoth/docx/body_xml.py#L344)

**Comment by dividor** [comment]
Thanks for looking into this, please find attached a test. The image in this document doesn't come through as a link, but is in the word file if unzipped.

[test.docx](https://github.com/mwilliamson/python-mammoth/files/882416/test.docx)

**Comment by mwilliamson** [comment]
Looks like the problem is that Mammoth doesn't understand `w:object` elements. From the looks of thing, it might be possible just to parse the children of `w:object` elements and the existing code should just work, but I haven't had a chance to actually try that.

**Comment by mwilliamson** [comment]
Should be working as of `f48379e`, just by reading the children of `w:object`. Hopefully there's nothing in there that we shouldn't be reading: if you could give the latest version on `master` a try, that would be appreciated.

**Comment by GitBruno** [comment]
That is a can of worms! It seems w:object is used to save [OLE data](https://en.wikipedia.org/wiki/Object_Linking_and_Embedding).

**Comment by mwilliamson** [comment]
Is that an issue? We ignore `OLEObject` elements since they're not explicitly supported.

**Comment by GitBruno** [comment]
No not at all! Just surprised by my findings. Sorry shouldn't use this as a chat.

**Comment by dividor** [comment]
Works perfectly, I see these images coming through now.

Many, many thanks!

**Comment by mwilliamson** [comment]
Great, thanks for checking.
