### ISSUE TITLE
Mammoth error when document has certain links

### ISSUE THREAD

**Issue by dividor** [mwilliamson/python-mammoth#32]
We have cases where sometimes the link in documents are broken, which we fix automatically another way. The problem is that Mammoth stops on error and doesn't process the document.

Attached are a sample document and the error we see.

Is there a way we can have Mammoth continue running please, so that it processes the full document?

thanks!

[Stuff2.docx](https://github.com/mwilliamson/python-mammoth/files/948977/Stuff2.docx)
[log.txt](https://github.com/mwilliamson/python-mammoth/files/948978/log.txt)

**Comment by mwilliamson** [comment]
Thanks for the report, this should be fixed in 1.3.5.

**Comment by dividor** [comment]
Fantastic! ... Just to please confirm for our planning - might you know when 1.3.5 might be available?

**Comment by mwilliamson** [comment]
It's already out.

**Comment by dividor** [comment]
Fantastic! Works a treat, thanks a lot.
