### ISSUE TITLE
Table header rows don't come through for tables

### ISSUE THREAD

**Issue by dividor** [mwilliamson/python-mammoth#34]
Attached is a sample document with a table. Mammoth produces a table like this ...

<table><tr><td><p><strong>The following variable…</strong></p></td><td><p><strong>Must be set to…</strong></p></td></tr><tr><td></td><td></td></tr><tr><td><p><code>SET STUFF</code></p></td><td><p>Stuff 1</p></td></tr><tr><td><p><code>SET STUFF 2</code></p></td><td><p>Stuff 2</p></td></tr><tr><td></td><td></td></tr></table>

So it doesn't specify that the first row is actually a header row.

Could Mammoth perhaps set the header row tag for this scenario?

thanks!
[table-headers.docx](https://github.com/mwilliamson/python-mammoth/files/959817/table-headers.docx)

**Comment by mwilliamson** [comment]
Looks like we could read the `w:tblHeader` from the table properties.

**Comment by Stikemanley** [comment]
Hello,

This is actually a feature that interests me as well. I'm currently coercing the first row of all tables to be the header and am running into downstream problems now with tables that shouldn't have a header row but now do due to my coercion. So the ability of mammoth to identify a header row would be very useful.

Is there an update?

Thanks!
Mike

**Comment by mwilliamson** [comment]
> Is there an update?

This is still unimplemented.

**Comment by mwilliamson** [comment]
Could you try the latest commit on `master` and see if that has the behaviour you expect?

**Comment by dividor** [comment]
Great! Will give it a go and let you know.

**Comment by Stikemanley** [comment]
Hey,

Just tried it out and it works beautifully, thanks for your hard work!!!

Best,
Mike

**Comment by dividor** [comment]
Yes, thanks loads!

**Comment by mwilliamson** [comment]
Glad it works.
