### ISSUE TITLE
How to convert one .docx contains a formulae to html ? It seems  that it is not supported? Can you give me another advice? thank you 

### ISSUE THREAD

**Issue by aslanxjc** [mwilliamson/python-mammoth#37]
How to convert one .docx contains a formulae to html ? It seems  that it is not supported?
Can you give me another advice? thank you

**Comment by mwilliamson** [comment]
Are you referring to Word's equation feature, or to formulas in tables? Neither is currently supported.

**Comment by mwilliamson** [comment]
Assuming this is a request for equation support, this is a duplicate of #17.
