### ISSUE TITLE
Markdown + output_dir?

### ISSUE THREAD

**Issue by benpolinsky** [mwilliamson/python-mammoth#38]
Is it possible to export images and also convert the docx file to markdown? I'm only able to convert to html when using a different output_dir.

Example:
```
mammoth a_doc_file.docx --output-dir=media --output-format=markdown
```

**Comment by mwilliamson** [comment]
When I try running the command, I get the output in Markdown, albeit in a file with an HTML extension. Does your output file contain HTML or Markdown?

**Comment by benpolinsky** [comment]
Ah yes, that is correct. HTML file extension, but clearly Markdown output.

**Comment by mwilliamson** [comment]
Should be a fairly easy fix to `cli.py` to pick the extension based on format.

**Comment by mwilliamson** [comment]
Although I should add that Markdown support isn't great -- if I needed the Markdown output myself, I'd be inclined to convert it to HTML and then use a separate HTML to Markdown converter.

**Comment by benpolinsky** [comment]
Right, right.
I've been wavering between Pandoc and Mammoth, so I'll stick to Pandoc for now.
If I have time and/or need, I'll try to put in a PR for this issue.

Thanks
