### ISSUE TITLE
Question: How to get highlighted or shaded text?

### ISSUE THREAD

**Issue by bitscompagnie** [mwilliamson/python-mammoth#39]
Hello, 

Thanks for your python-mammoth, which I have just started trying and find that it has a potential.

How can we create custom style map for the highlighted or shaded text. From examining document.xml I see the following for shaded text: 
`<w:pPr><w:shd w:val="clear" w:color="auto" w:fill="FF0000"/>` ;
and this one for highlighted text:  `<w:highlight w:val="lightGray"/>`

I have tried following code without success:

`style_map = """
p[style-name='highlight'] => p.myclass1:fresh
p[style-name='shd'] => p.myclass2:fresh
"""`
Thanks,

**Comment by mwilliamson** [comment]
To use style maps in the way you've described, you need to define a character style in Word called "highlight" or "shd" (with appropriate formatting) and apply the character style to the text, rather than setting the highlight or shading directly on the text.

**Comment by bitscompagnie** [comment]
Thanks for your reply. That worked fine.
