### ISSUE TITLE
Docx images are linked, not embeded

### ISSUE THREAD

**Issue by beta1042** [mwilliamson/python-mammoth#4]
Python 2.7
Traceback error: 
File "build\bdist.win32\egg\mammoth\docx\document_xml.py", line 233, in _read_blip
    relationship_id = element.attributes["r:embed"]
KeyError: 'r:embed'

I have a word document that was originally created from a html document (I know, and now I need html again). So images were created from the href file links. When I try to convert the word document, the KeyError for r:embed occurs. I think this is linked back to the a:blip tag in the xml which has a r:link attribute referencing an image reference rather than a r:embed attribute.

In one case, this is an example (from document.xml): 
```
<pic:blipFill><a:blip r:link="rId8"><a:extLst><a:ext uri="{28A0092B-C50C-407E-A947-70E740481C1C}"><a14:useLocalDpi xmlns:a14="http://schemas.microsoft.com/office/drawing/2010/main" val="0"/></a:ext></a:extLst></a:blip>
```
And from my document.xml.rels file: 
```
<Relationship Id="rId8" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="file:///\\serverpath\Images\addins_go.png" TargetMode="External"/>
```

I'd like to have the image files linked to a file path again in an image tag if that is possible.

If you have any suggestions or need further information, I'll try to get back with you in a timely manner.

**Comment by mwilliamson** [comment]
Thanks for the report! It all makes sense to me, I'll take a look when I get a chance, although that might not be for a few days.

**Comment by beta1042** [comment]
This is handy code. Thank you.

I've at least coded up to have Word break the links and embed images for documents I generate. But I figure it may still come up with other users or other files I may get / have. So I'll implement any future enhancement when it gets sorted out... meaning a few days or more is fine.

As far as saving out the image files, it finally hit me that I'm re-implementing (or at least providing) the convert_image def and am now decoding the image string and writing out individual image files to a sub-directory.

**Comment by mwilliamson** [comment]
Just to check: are you expecting the image to have the exact same URL in the outputted HTML, or to be treated the same as other images in the document (which means the image could either be included inline or written out to a new file on disk)? The latter is easier to implement (since it'll be the existing behaviour), but I'd consider supporting the first if there's a reason you'd prefer it.

**Comment by beta1042** [comment]
I guess the biggest help would at least be able to access the target URL. Whether that be an additional attribute of the documents.Image object or not (similar to "alt_text", which took a little digging to find). If it was held on to then a user could implement the img tag however they choose to (inline, written out, or still linked). You could then still keep the current default implementation and the target URL could be "None" unless one was there.

**Comment by mwilliamson** [comment]
I've just uploaded 0.3.20 to PyPI, could you try it out and see if it fixes your issue? This should treat linked images the same as embedded images.

**Comment by beta1042** [comment]
I tried the new 0.3.20 release and it does resolve the issue I was encountering. Thank you for the update.
