### ISSUE TITLE
target frame in a href?

### ISSUE THREAD

**Issue by ssehovic** [mwilliamson/python-mammoth#42]
Hi Michael,

Is it possible to add switch to cli when parsing word document a href links get target=_blank or any other target frame? Seems that there is no option in Mac word when editing hyperlink to add target frame.

S.

**Comment by mwilliamson** [comment]
Mammoth just reads the target frame from the source document, so if
Word for OS X doesn't support editing the target, then you can't get
Mammoth to generate different targets.

If you need all links to be be in new windows, then I'd suggest adding
in a post-processing step to add a target to anchor tags.

**Comment by ssehovic** [comment]
How can I do that, post-processing? By manually add target=_blank to a href ?

**Comment by mwilliamson** [comment]
You could do it manually, or find a tool that lets you:
* parse the HTML
* add a target="_blank" attribute to each anchor
* serialise the HTML back to a string

**Comment by ssehovic** [comment]
Ok, thanks for reply.
