### ISSUE TITLE
Style names with non-ASCII characters not recognized in Python 2

### ISSUE THREAD

**Issue by pysailor** [mwilliamson/python-mammoth#44]
Hi,
I am really happy that I discovered mammoth today, it's a great tool!

I have a problem with one detail, though: I want to convert a docx file from a German user, and need to define some custom styles. And of course, some of the styles contain an umlaut...
**Note**: I'm using python2.7

Concrete example: The style for displaying a numbered listing is called "Aufzählung", and a variant of this, where the numbers are Roman I II III instead of Arabic 1 2 3, is called "Aufzählung Römisch". By default, mammoth does not recognize that paragraphs with these styles need to be a listing. 

So I define my custom style_map:
```
style_map = """
p[style-name='Aufzählung'] => ol > li:fresh
p[style-name='Aufzählung Römisch'] => ol.roman > li:fresh
"""
```
Only to find that paragraphs with those styles are still not recognized as listings. If I rename the styles to plain ASCII, e.g. "Listing Roman" in my sample and in the style_map, all is fine.

Some debugging led me to https://github.com/mwilliamson/python-mammoth/blob/master/mammoth/document_matchers.py#L60, where this Warning happens: 
`UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal`.
In my test, `second`, which comes from the sample Word file, is the unicode string `u'Aufz\xe4hlung'`, and `first` is the byte string `'Aufz\xc3\xa4hlung'` - so comparing fails. If `first` were also decoded to unicode using utf-8, they would be recognized as equal:
```
'>>> Aufz\xc3\xa4hlung'.decode('utf-8').upper() == u'Aufz\xe4hlung'.upper()
True
```
(Again, note: If I test this using python3.5, it all works. But my application is still using python2.7, where this problem occurs.)

If I make the following code changes: https://github.com/mwilliamson/python-mammoth/compare/master...syslabcom:master, then my sample Word file works fine (I get my `<ol>` tags like I want). But obviously, this code will break under Python 3, since `basestring` and `unicode` have been removed.

Therefore: 
1) Do you care about supporting this use-case also under Python 2? 
2) And if yes, what would you think is a sensible approach for supporting both 2 and 3? I'm willing to contribute, but my experience with Python 3 so far is rather limited.

**Comment by mwilliamson** [comment]
Thanks for the report: yes, this should be fixed. Both strings in the comparison are being parsed, one from the document XML, and the other from the style map. If you work out which one is producing the bytestring, then the best fix is to change that parser to always produce unicode strings.

**Comment by mwilliamson** [comment]
Just read what you posted more carefully: the bytestring is coming from the style map. Are you passing in a `bytes` instance or a `unicode` instance as the `style_map` argument? Unless you have the unicode strings future import, then it seems like you'd want:

```python
style_map = u"""
p[style-name='Aufzählung'] => ol > li:fresh
p[style-name='Aufzählung Römisch'] => ol.roman > li:fresh
"""
```

**Comment by pysailor** [comment]
By Jove, that's it, of course!
I was simply too blind to see that.
So this is actually a non-issue - all is working fine!
