### ISSUE TITLE
chart r:id

### ISSUE THREAD

**Issue by war21x3b** [mwilliamson/python-mammoth#45]
Hello. Very glad to use your wonderful mammoth tool.
I have a problem with charts. I understand what mammoth do not convert charts today. 
But, i need to put into html `chart r:id` from docx.

Are there any ways to do this?

**Comment by mwilliamson** [comment]
I'm afraid I don't quite understand your question. You want to include the `r:id` attribute in the HTML? There's currently no way to do so.

**Comment by war21x3b** [comment]
Thanks for your reply.
