### ISSUE TITLE
How to set table class using style maps?

### ISSUE THREAD

**Issue by bitscompagnie** [mwilliamson/python-mammoth#46]
Hello, 
```
<w:tbl>
            <w:tblPr>
                <w:tblStyle w:val="tableone"/>
                <w:tblW w:w="0" w:type="auto"/>
                <w:tblLook w:val="04A0" w:firstRow="1" w:lastRow="0" w:firstColumn="1"
                    w:lastColumn="0" w:noHBand="0" w:noVBand="1"/>
            </w:tblPr>
            <w:tblGrid>
```

With the above document excerpt, I am trying to set a class on the table styled with **tableone** style name.
I am using the following style_map but the output is not giving me the desired result, which should be
`<table class="mytableone"></table>` as specified in below style map settings:
```
style_map = """
tbl[style-name='tableone'] => table.mytableone:fresh
table[style-name='tableone'] => table.mytableone:fresh
"""
```
None of the above produces the needed output.

What is the best way to set table classes using Mammonth's style map settings?

Thanks for your reply.

**Comment by mwilliamson** [comment]
Style maps don't currently support tables, so there's no way to directly set the class on tables.

**Comment by bitscompagnie** [comment]
Thanks for your reply. 

Would you kindly consider adding it?

**Comment by mwilliamson** [comment]
There's no reason not to add it, but I have no idea when I'd have time to do so.

**Comment by bitscompagnie** [comment]
What would be the best way to add style maps for tables to mammoth? Any suggestions about the file(s) to modify? Or the way to create a custom function to do that?

I saw below function in document_matcher_parser.py. 
```
def parse_document_matcher(tokens):
    if tokens.try_skip(TokenType.IDENTIFIER, "p"):
        style_id = try_parse_class_name(tokens)
        style_name = _parse_style_name(tokens)
        numbering = _parse_numbering(tokens)
        
        return document_matchers.paragraph(
            style_id=style_id,
            style_name=style_name,
            numbering=numbering,
        )
.....
```

Is the above the file to modify for style maps support for tables?

Thanks for your reply.

**Comment by mwilliamson** [comment]
Style mappings for tables are supported as of 1.4.3.

**Comment by bitscompagnie** [comment]
Thanks a lot,

I will test it.

**Comment by bitscompagnie** [comment]
I just tested setting a class on a table based on it's style ID and it worked fine.

Thanks very much.

**Comment by ssudhak** [comment]
@bitscompagnie @mwilliamson , Not sure if its working for me. Can you help me understand now to test it. I was trying something like below code.

table[style-name='body-st'] => div.body-st > table:fresh
