### ISSUE TITLE
Save original graphic size

### ISSUE THREAD

**Issue by GitBruno** [mwilliamson/python-mammoth#47]
What is the best way to get original image size? Getting that information post-processing is a pain in the butt especially for those emf base64 graphics.

It would be hugely helpful if we could save the **original** sizes (Not the scaled canvas) to the img height and width attribute, (semantic info)

    --output-image-size=original
    --output-image-size=none (Standard behaviour)

    <img src="data:image/x-emf;base64,AZX.." width="150pt" height="50pt">

I don't really mind to which units to save them, I guess it would be great to use points as there would be no confusion about DPI. (MS Office seems to process everything at 72DPI if we went with pixels).

We can find the original dimensions inside the shape property: `<a:ext cx="1905000" cy="635000"/>`  These use the English Metric Units (914400 EMUs per inch) So it should be straightforward to convert those?

Or we can pass the all sizing info the [image class](https://github.com/mwilliamson/python-mammoth/blob/master/mammoth/images.py) so it will be easier for people to create a custom [image converters](https://github.com/mwilliamson/python-mammoth#image-converters)

What do you think?

**Comment by mwilliamson** [comment]
Putting the units onto the image object seems fine to me, although it's probably worth checking the different ways of embedding images that Mammoth currently supports.

**Comment by GitBruno** [comment]
I don't have a lot of experience with image conversion with mammoth but it looks perfect for pixel based formats, I try to preserve some embedded vector graphics.

Simply passing the original data on to the image object is sweet. I'll prep a pull request sometime next week. Thanks!

**Comment by charanjit-singh** [comment]
I'm facing same issue

**Comment by GitBruno** [comment]
I created a custom [image handler](https://github.com/mwilliamson/python-mammoth#image-converters) using PIL to get image information:

    import base64
    import io
    from PIL import Image

    # An example of how to add the source file dimensions to the img tag
    # mammoth.convert_to_html(docx_file, convert_image=mammoth.images.img_element(add_dimensions))
    
    def add_dimensions(image):

        with image.open() as image_source:
            image_bytes = image_source.read()
            encoded_src = base64.b64encode(image_bytes).decode("ascii")
            img_size = Image.open(io.BytesIO(image_bytes)).size
    
        img = {
            "src": "data:{0};base64,{1}".format(image.content_type, encoded_src)
        }

        if img_size:
            img["width"]  = str(img_size[0]);
            img["height"] = str(img_size[1]);

        return img

It might be a good idea to add this to the [recipes](https://github.com/mwilliamson/python-mammoth/tree/master/recipes) @mwilliamson either way, I will close this issue.
