### ISSUE TITLE
Pre converted html tags in doc file

### ISSUE THREAD

**Issue by anvinj** [mwilliamson/python-mammoth#49]
Is there any option to ignore the html conversion of pre-converted (html statements) in the input docx file.
ie if the input file contains few html tags, can we avoid the conversion for those statements.

**Comment by mwilliamson** [comment]
Do you mean HTML that appears in `w:altChunk` elements (so `<strong>hello</strong>` would appear as the text "hello" in bold), or HTML that literally actually appears in the document (so the text would literally be `<strong>hello</strong>`)? The former isn't supported by Mammoth at the moment, so there's no need for an option. The only way you'd be able to strip out the latter would be to use a document transform, as described in the docs.

**Comment by anvinj** [comment]
Following is a part of doc am trying to convert to html.

Options:
(a) Acidic &#58; NH<sub>3</sub> < PH<sub>3</sub> < AsH<sub>3</sub> 

Here i have to retain the html tags while converting.
Any help will be appreciated. 
Thanks in advance

**Comment by mwilliamson** [comment]
I'm afraid I don't follow. Looking at your example, I think everything there should be supported. For instance, subscript is already. If you could provide an example document and the output you expect, then that would help.
