### ISSUE TITLE
mammoth: error: argument --output-dir: not allowed with argument output

### ISSUE THREAD

**Issue by ikito** [mwilliamson/python-mammoth#5]
root@DS:/var/www/html/ds/filebox/12/33/docx# mammoth test.docx index.html --output-dir=images
usage: mammoth [-h] [--output-dir [OUTPUT_DIR]]
               [--output-format {markdown,html}] [--style-map STYLE_MAP]
               path [output]
mammoth: error: argument --output-dir: not allowed with argument output

I can't see where is the problem.

**Comment by mwilliamson** [comment]
The problem is as the error message describes: you can either set an output file, or an output directory, but not both. In your case, you've set the output file to `index.html`, and the output directory to `images`.

**Comment by ikito** [comment]
Thanks, that's right.
