### ISSUE TITLE
find bold paragraphs

### ISSUE THREAD

**Issue by fiee** [mwilliamson/python-mammoth#51]
I’m trying to find a style mapping that turns all-bold paragraphs into headings:

    p:fresh > b => h2

But I get the error "Did not understand this style mapping, so ignored it: p:fresh > b => h2"
(The same without :fresh)

Where’s my mistake?

**Comment by mwilliamson** [comment]
What you're describing isn't currently possible. The recommended approach is instead to make the paragraphs bold using a Word paragraph style, and then map that paragraph style to a CSS style.

If you can't change the source documents, you can use a document transform instead, although this is fiddler to get working consistently depending on what your documents look like.

**Comment by fiee** [comment]
A pity. I don’t want to touch all manuscripts before processing, so I’ll use some regex.
Thank you anyway.
