### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by fiee** [mwilliamson/python-mammoth#52]
In my projects often the language of a document (or paragraph or text run like quotations) is important for the conversion. I don’t know if this information is in DOCX at all, but if, it would be nice to be able to use it optionally as "lang" attributes.

**Comment by mwilliamson** [comment]
I've no idea whether this information is stored in the document, but it seems like adding a lang attribute could be done outside of Mammoth?

**Comment by fiee** [comment]
Not in my workflow – I thought maybe you’d know about DOCX internals. I’ll keep marking up language changes manually. (Really important they’re only for script changes, i.e. Greek or Cyrillic, and those I can find via regex character ranges.)
