### ISSUE TITLE
Math/Ml issue

### ISSUE THREAD

**Issue by namangupta01** [mwilliamson/python-mammoth#54]
Hey. I am using math/ml equations directly in my doc file. 
`<math xmlns="http://www.w3.org/1998/Math/MathML"><msubsup><mo>&#x222B;</mo><mrow><mi>cos</mi><mfenced><mrow><mi>tan</mi><mfenced><mrow/></mfenced></mrow></mfenced></mrow><mrow><mi>sin</mi><mfenced><mrow><msub><mi>log</mi><mrow/></msub><mfenced><mrow/></mfenced></mrow></mfenced></mrow></msubsup></math>`

I want this text not to get convert to html that is i want this data to remain as it is how can i do that?
Thank You!

**Comment by mwilliamson** [comment]
I'm afraid this currently isn't supported.

**Comment by namangupta01** [comment]
Oh okay! And also is there any way that the image in the doc come relative to the the size in doc not in its original big size while converting it to html?

**Comment by mwilliamson** [comment]
Again, I'm afraid not. Closing since equation support and image sizes are already reported in issues #17 and #47 respectively.
