### ISSUE TITLE
Support w:sym elements

### ISSUE THREAD

**Issue by Mrfuyu** [mwilliamson/python-mammoth#55]
There's currently no support of arrows that are generated by word automatically when typing `-->`. 

It should be converted to HTML arrows like `&rarr;`

**Comment by mwilliamson** [comment]
Could you provide an example document, and the result of attempting to convert it, including both the generated HTML and the messages?

**Comment by Mrfuyu** [comment]
`mammoth arrow_example.docx arrow_example.html` throws `An unrecognised element was ignored: w:sym` and output

`<h1>Example of an auto-generated arrow pointing to the right</h1><p>Autogenerated arrows are very common in my use  it would be nice to see them converted by python-mammoth.</p><h1>Example of an auto-generated arrow pointing to the left</h1><p>Foobar What should be a foobar???</p>`

[arrow_example.docx](https://github.com/mwilliamson/python-mammoth/files/1799275/arrow_example.docx)

**Comment by mwilliamson** [comment]
Looks like support for the `w:sym` element is missing. There's a similar issue for mammoth.js: https://github.com/mwilliamson/mammoth.js/issues/144

**Comment by mwilliamson** [comment]
Symbols should now be supported for a subset of fonts (Symbol, Webdings, Wingdings, Wingdings 2 and Windings 3).

**Comment by Cazforshort** [comment]
Anyway this could be used to replace all the w:sym in a word doc with their unicode codes or something? python-docx still doesn't support reading them so I can't replace them or find them in documents.
