### ISSUE TITLE
character conversion issue?

### ISSUE THREAD

**Issue by paklein** [mwilliamson/python-mammoth#60]
docx contains the Euro symbol:
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 39572: ordinal not in range(128)

**Comment by mwilliamson** [comment]
Could you post a full stack trace and an example document?

Could you also post how you're invoking Mammoth, either on the command line (if using the CLI) or in code (if using it as a library)?

**Comment by GitBruno** [comment]
I don't think this is an issue, but rather an issue of implementation. See similar issues on [Stackoverflow](https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20). Said that, happy to write a unicode test to close this issue.

**Comment by mwilliamson** [comment]
Closing since there's not much I can do without further information.

**Comment by paklein** [comment]
Sorry for the long delay. Example attached.
[test.docx](https://github.com/mwilliamson/python-mammoth/files/2333575/test.docx)
