### ISSUE TITLE
.docx missing word/styles.xml throws exception

### ISSUE THREAD

**Issue by RoyIacob** [mwilliamson/python-mammoth#62]
Documents that don't have "word/styles.xml" will throw an exception.

In docx/\_\_init\_\_.py:40, the code runs ```_open_entry``` without first checking for the property.

I corrected it in a local build by wrapping it with ```_has_entry```, and returning an empty Styles object.

I modified the constructor of Styles to get an empty styles constructor.

```Python
    def __init__(self, paragraph_styles=None, character_styles=None):
        if paragraph_styles and character_styles:
            self._paragraph_styles = paragraph_styles
            self._character_styles = character_styles
        else:
            self._paragraph_styles = {}
            self._character_styles = {}
```

I wanted to know if this is a good way to handle the issue.

**Comment by mwilliamson** [comment]
Do you have an example document? It'd be useful to know whether the styles file is completely missing, or whether Mammoth is failing to find it.

Rather than changing the constructor, I'd suggest a better approach would be to create the object with empty dictionaries explicitly, since missing out arguments should be an error in other cases.

**Comment by RoyIacob** [comment]
I would love to send it but unfortunately, it has too much sensitive data on it. Im afraid making a copy would probably augment the file with the missing styles.xml.

in `mammoth/docx/__init__.py:39`:

```Python
zip_file.printdir()

# outputs:

# File Name                                             Modified             Size
# _rels/.rels                                    2017-09-15 14:09:14          594
# [Content_Types].xml                            2017-09-15 14:09:14          807
# docProps/app.xml                               2017-09-15 14:09:14          183
# docProps/core.xml                              2017-09-15 14:09:14          502
# word/document.xml                              2017-09-15 14:09:14        13054
# word/_rels/document.xml.rels                   2017-09-15 14:09:14          290
# word/settings.xml   
````

**Comment by mwilliamson** [comment]
Would you mind taking a look inside `word/_rels/document.xml.rels`, and seeing if there's anything with a `Type` of `http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles`, or any other `Type` that looks like it might be a styles file?

**Comment by RoyIacob** [comment]
`word/_rels/document.xml.rels`:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Target="settings.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"/>
</Relationships>
```

**Comment by RoyIacob** [comment]
Let me know if there are any other details I can provide

**Comment by RoyIacob** [comment]
Issue was fully corrected by using most up to date version.

I was using a 0.x version. My bad!
