### ISSUE TITLE
the red color font in docx lost color after transform to html.

### ISSUE THREAD

**Issue by kingctan** [mwilliamson/python-mammoth#65]
the red color font in docx lost color after transform to html.
and I add this line to style map:
```
r[style-name='Red'] => span.red
```
it's not work,
please help, Thanks a lot.

**Comment by mwilliamson** [comment]
Are you trying to convert text that's had the red colour applied to it, or that has a style called "Red" applied to it? The style map you've listed will only work with the latter.

**Comment by kingctan** [comment]
sorry, 
i am new to the docx process. How to find the text which has red colour or has style called "Red"?
Thanks .

**Comment by GitBruno** [comment]
1. Open Word
  2. Create a new character style called `Red`
  3. Open Find & Replace dialog
  4. Under `Find` set `Color` to `Red` (The swatch)
  5. Under `Replace` set `character style` to `Red` (The character style)
  6. Hit `Replace all`

Now all the red text will be styled with the red character style. After conversion with Mammoth and style map the 'red' text will be surrounded by `span.red` in your HTML.

For the tagged text to actually appear red, you will need to add some CSS:

    span.red {
        color: red;
    }

**Comment by fdabek1** [comment]
@GitBruno I have a large amount of Word documents that I am trying to get an HTML that looks as similar to the original document as possible.  Therefore, going through and doing the find and replace manually would be too cumbersome.

I would like to be able to use the style maps, but it seems that mammoth only looks at the Word Styles, correct?  Is there a way to get the XML of a paragraph/document to be able to get the font colors applied?  Or do I need to parse the XML by myself without using something like Mammoth as a base?

**Comment by mwilliamson** [comment]
Mammoth intentionally doesn't try to copy the formatting of the original document, so if that's your goal, then Mammoth likely isn't the right tool for the job.

**Comment by GitBruno** [comment]
If that is your goal give [XSweet](https://gitlab.coko.foundation/XSweet/XSweet) a go. It is far from perfect but it might suit your needs.

**Comment by fdabek1** [comment]
@GitBruno Oh this is fantastic!  Thanks a lot!

However, to look for a python solution have you guys ever thought of adding a styled output approach to mammoth?  One that would allow the user to select which type of output to have.  Is this something that would be best as a PR request or a fork?

Also for future reference of anybody that comes across this issue looking for a Windows only solution: https://stackoverflow.com/questions/6011115/doc-to-pdf-using-python/6018039

**Comment by mwilliamson** [comment]
> However, to look for a python solution have you guys ever thought of adding a styled output approach to mammoth? One that would allow the user to select which type of output to have. Is this something that would be best as a PR request or a fork?

Other existing tools, such as Word's own HTML export, already attempt to generate HTML with the same exact formatting. Mammoth has document transforms to allow structure to be inferred from a document that may not have been semantically marked up, but since other tools exist for other use cases, Mammoth will stick to producing semantic HTML.

**Comment by caramdache** [comment]
> If that is your goal give [XSweet](https://gitlab.coko.foundation/XSweet/XSweet) a go. It is far from perfect but it might suit your needs.

I had a rather disappointing experience with XSweet. It's slow, requires to run a shell script, to store documents in an "inbox" folder and to retrieve the output in an "outbox" folder. And it mangled most of my Word formatting, including tables and colours. Installation and update is just a nightmare, compared to `pip`.

For my use case, fast and easy python integration, mammoth is a much better match; except for colours but that is solved by issue https://github.com/mwilliamson/python-mammoth/issues/63

I don't think there is any harm in keeping the colour. I would even be willing to go as far as say that colour could be regarded as semantic information, in particular in use cases I am dealing with. People may not be disciplined enough to use styles, but their intent is certainly to associate certains portions of the document with a semantic represented by a certain colour and we should be able to retain this. For example by using the `<marker>` element.

**Comment by caramdache** [comment]
I went a step further and implement support for table cell fill colour. This was necessary for my use case.

https://github.com/mwilliamson/python-mammoth/pull/117
