### ISSUE TITLE
UnicodeEncodeError Exception

### ISSUE THREAD

**Issue by mahower** [mwilliamson/python-mammoth#70]
Using the CLI to convert the attached file [38331-f30.docx](https://github.com/mwilliamson/python-mammoth/files/2542832/38331-f30.docx)results in the following output:

> PS 
mammoth .\38331-f30.docx output.html
Image of type image/x-emf is unlikely to display in web browsers
An unrecognised element was ignored: {urn:schemas-microsoft-com:office:office}OLEObject
Image of type image/x-wmf is unlikely to display in web browsers
An unrecognised element was ignored: w:tblPrEx
Unrecognised paragraph style: ZA (Style ID: ZA)
Unrecognised paragraph style: ZB (Style ID: ZB)
Unrecognised paragraph style: ZT (Style ID: ZT)
Unrecognised run style: ZGSM (Style ID: ZGSM)
Unrecognised paragraph style: ZU (Style ID: ZU)
Unrecognised paragraph style: FP (Style ID: FP)
Unrecognised paragraph style: TT (Style ID: TT)
Unrecognised paragraph style: toc 1 (Style ID: TOC1)
Unrecognised paragraph style: toc 2 (Style ID: TOC2)
Unrecognised paragraph style: toc 3 (Style ID: TOC3)
Unrecognised paragraph style: toc 4 (Style ID: TOC4)
Unrecognised paragraph style: toc 5 (Style ID: TOC5)
Unrecognised paragraph style: toc 8 (Style ID: TOC8)
Unrecognised paragraph style: B1 (Style ID: B1)
Unrecognised paragraph style: B2 (Style ID: B2)
Unrecognised paragraph style: B3 (Style ID: B3)
Unrecognised paragraph style: EX (Style ID: EX)
Unrecognised paragraph style: EW (Style ID: EW)
Unrecognised paragraph style: Editor's Note (Style ID: EditorsNote)
Unrecognised paragraph style: TH (Style ID: TH)
Unrecognised paragraph style: TF (Style ID: TF)
Unrecognised paragraph style: NO (Style ID: NO)
Unrecognised paragraph style: B4 (Style ID: B4)
Unrecognised paragraph style: B5 (Style ID: B5)
Unrecognised paragraph style: B6 (Style ID: B6)
Unrecognised paragraph style: B7 (Style ID: B7)
Unrecognised paragraph style: EQ (Style ID: EQ)
Unrecognised paragraph style: B8 (Style ID: B8)
Unrecognised paragraph style: TAH (Style ID: TAH)
Unrecognised paragraph style: TAL (Style ID: TAL)
Unrecognised paragraph style: PL (Style ID: PL)
Unrecognised paragraph style: TAC (Style ID: TAC)
Unrecognised paragraph style: heading 8 (Style ID: Heading8)
Traceback (most recent call last):
  File "c:\users\mhowerto\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mhowerto\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mhowerto\AppData\Local\Continuum\anaconda3\Scripts\mammoth.exe\__main__.py", line 9, in <module>
  File "c:\users\mhowerto\appdata\local\continuum\anaconda3\lib\site-packages\mammoth\cli.py", line 40, in main
    output.write(result.value)
  File "c:\users\mhowerto\appdata\local\continuum\anaconda3\lib\site-packages\mammoth\cli.py", line 80, in write
    self._fileobj.write(value)
  File "c:\users\mhowerto\appdata\local\continuum\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2011' in position 46304: character maps to undefined>

**Comment by mwilliamson** [comment]
It looks like the default encoding on your Windows machine doesn't support one of the characters in your document. I don't have a Windows machine to hand to test, but perhaps setting `PYTHONIOENCODING=utf-8:surrogateescape` in your environment variables would help as a temporary fix? I'll update the CLi to always use UTF-8 to write to files.

**Comment by mwilliamson** [comment]
I've just released 1.4.7, which should hopefully the fix the issue. Could you give it a try?

**Comment by mwilliamson** [comment]
Closing in the hope that this is fixed, feel free to reopen if that's not the case.
