### ISSUE TITLE
Converting List Paragraphs to Unordered Lists 

### ISSUE THREAD

**Issue by fsecada01** [mwilliamson/python-mammoth#78]
I'm working with this sample file to convert the entire thing to Markdown.  While this is largely successful, I am not able to adequately transform paragraphs containing lists into unordered lists.  I've attempted to write out a transform function for each element, but it seems that Mammoth does not have a default set of style values for lists, despite this being standard with .docx, .odt, and .md filetypes.

```
default_docx_style_list = set([ele.name for ele in list(docx.Document().styles)])
```

```
def transform_paragraph(element):
    if element.style_id == 'ListParagraph' or 'PositionDetails':
        return element.copy(style_id='List', style_name = 'List')
    else:
        return element


transform_document = transforms.paragraph(transform_paragraph)

with open(file_loc, 'rb') as docx_file:
    html_result = mammoth.convert_to_html(docx_file, transform_document=transform_document)
    md_result = mammoth.convert_to_markdown(docx_file, transform_document=transform_document)
    
    markdown = md_result.value
    html = html_result.value
    md_messages = md_result.messages
    html_message = html_result.messages
```
Output from md_messages
```
[Message(type='warning', message='An unrecognised element was ignored: w:cr'),
 Message(type='warning', message='Unrecognised paragraph style: List (Style ID: List)')]
```

[Francis_Secada_-_Tech_Resume_-_ATS_Format_-_January_2019.docx](https://github.com/mwilliamson/python-mammoth/files/3061469/Francis_Secada_-_Tech_Resume_-_ATS_Format_-_January_2019.docx)

**Comment by mwilliamson** [comment]
Rather than using a document transform, use a style map to convert styles in Word to the appropriate HTML. For instance:

```
'p.ListParagraph => ul > li:fresh'
```
