### ISSUE TITLE
Add support for formatting of tables

### ISSUE THREAD

**Issue by humla2k** [mwilliamson/python-mammoth#79]
Hi, and thanks for doing a great job!
As for now, formatting of tables is ignored. Do you have plans on implementing such feature or can you give a hint where to start if I want to give it a try myself?

My situation is as follows: I have a large number of doxc files, all of them with at least three tables, all of them is presented differently regardning borders on either cell or table. Additionally, some tables have different width's, depending of content type. My solution today is to, as you describe, use css to style the tables (each table gets an id from a python script). Somtimes, when adding a new table for instance, the id changes for a table and I have to alter the css-file accordingly. And with about 400 tables, it's quite a job to do..

Best regards

**Comment by mwilliamson** [comment]
If you assign an appropriate style to the table, you should be able to use style mappings to map from the Word style to an appropriate CSS class.

**Comment by ahsanshakil9700** [comment]
Can anyone write a sample style map for adding borders to a normal table created using word. I can't seem to understand that

**Comment by rajeshpyne** [comment]
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>
</head>
<body>
....
</body>
</html>
