### ISSUE TITLE
'_io.BytesIO' object had no attribute 'name'

### ISSUE THREAD

**Issue by joshclow** [mwilliamson/python-mammoth#8]
Looks like line 31 of docx/__init__.py was changed a couple revs back to be:

`body_readers = _body_readers(getattr(fileobj, "name"), zip_file)`

We're calling mammoth.convert_to_html with a io.BytesIO stream and so it doesn't have a name attribute and the code bombs out with the AttributeError in the issue title. Is there an intentional design decision here to restrict the code to objects with name attributes?

**Comment by mwilliamson** [comment]
This was an oversight on my part: support was added for images that are stored externally relative to the documents location on disk, which requires knowing where the document is stored, but the intention wasn't to completely break support for using file objects without names. I'll see how hard it is to fix.

**Comment by mwilliamson** [comment]
This should be fixed as of 0.3.22, please let me know if this isn't the case.

**Comment by joshclow** [comment]
That sorted it, thanks much!
