### ISSUE TITLE
setup.py refers to README

### ISSUE THREAD

**Issue by dwasyl** [mwilliamson/python-mammoth#80]
Hi there,

Currently, the `setup.py` file refers to a README file on line 21 `long_description=read("README"),` this line should read `README.md`.

**Comment by mwilliamson** [comment]
`README` is generated using `README.md` (there's a target in the makefile).

**Comment by dwasyl** [comment]
@mwilliamson strange, I get build errors with pip. Must be another issue on my pip build then. Thanks

**Comment by dwasyl** [comment]
@mwilliamson Do you know if there an easy way to get pip to run the Makefile on install then? Whenever I try to install directly from github I get this error and would love to get around it).
