### ISSUE TITLE
python setup.py install fails:  No such file or directory: 'README'

### ISSUE THREAD

**Issue by akkana** [mwilliamson/python-mammoth#81]
Is installing from source supported? Very minor bug: when I try to install from the git source, setup.py is looking for a file called README.

`$  python setup.py install
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    long_description=read("README"),
  File "setup.py", line 8, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
FileNotFoundError: [Errno 2] No such file or directory: 'README'
zsh: exit 1     python setup.py install
`

The actual file is named README.md. This fixed the install (but I don't know if .md files are considered valid in Python packages; I hope so, I use them too):

`diff --git a/setup.py b/setup.py
old mode 100644
new mode 100755
index fc441b0..ff2038e
--- a/setup.py
+++ b/setup.py
@@ -19,7 +19,7 @@ setup(
     name='mammoth',
     version='1.4.9',
     description='Convert Word documents from docx to simple and clean HTML and
-    long_description=read("README"),
+    long_description=read("README.md"),
     author='Michael Williamson',
     author_email='mike@zwobble.org',
     url='http://github.com/mwilliamson/python-mammoth',
`
Thanks, as always, for mammoth -- I use it all the time, it makes dealing with Word users bearable. :-)

**Comment by mwilliamson** [comment]
I think this is the duplication of #80: `README` is generated using `README.md` (there's a target in the makefile).

**Comment by dwasyl** [comment]
@akkana Did you ever find a solution for building the `README` file as part of `pip install`? I am still doing it manually many years later.
