### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by eladbitton** [mwilliamson/python-mammoth#82]
Is there a way to know where each page start in the generated html?

**Comment by GitBruno** [comment]
If you talk about page breaks you can use style maps to mark a post processing to count.

    br[type='page'] => br.page

If you talk about natural page breaks this is covered in issue #61 <w:lastRenderedPageBreak />

**Comment by mwilliamson** [comment]
I'm probably coming around to the opinion that page breaks don't map naturally into HTML documents, so Mammoth is unlikely to support them. As pointed out, #61 already tracks this.
