### ISSUE TITLE
Multilevel class not converting

### ISSUE THREAD

**Issue by rageshchalil** [mwilliamson/python-mammoth#83]
Have a word document with have multi-level styles, which does not seem to convert properly. attaching here a sample. 

[sample.docx](https://github.com/mwilliamson/python-mammoth/files/3859811/sample.docx)

Another question I have is regarding the multi-level ordered list and numbered lists, and the level can go deep to 6 at least. Is there a standard way of writing this?

**Comment by rageshchalil** [comment]
@mwilliamson can you please help with this issue here?

**Comment by mwilliamson** [comment]
I'm not sure what behaviour you're expecting. What is the HTML you're expecting?

**Comment by rageshchalil** [comment]
@mwilliamson Should like this:
<div class="wrapperbody">
Some data on body class. A bold text here. Remaining part of the text. 
For  <div class="nonexistent">[or see accompanying or see attached — pick appropriate location]</div> full Information available on guide.
those of their respective owners.
</div>

**Comment by mwilliamson** [comment]
You'll need to mark up the different sections of text using different styles in Word, and convert those Word styles to CSS classes using style mappings.

**Comment by rageshchalil** [comment]
Thanks for your response @mwilliamson, my question was how do we write style map when we have multi-level custom style document. In this case "bodyisi" and  "IGNORE" which is inside the earlier one.

**Comment by mwilliamson** [comment]
I'm not sure what you mean by "multi-level" in this case. It seems like you'd want something like:

```
p[style-name='IGNORE'] => !
r[style-name='IGNORE char'] => !
```

to ignore those styles.

**Comment by rageshchalil** [comment]
@mwilliamson, this kind of helped me resolve my issues.
how can I know various type of rules that I can set in custom maps? eg: the one you set above with => !

**Comment by mwilliamson** [comment]
The rules are documented in the README: https://github.com/mwilliamson/python-mammoth#writing-style-maps
