### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by thainquet** [mwilliamson/python-mammoth#89]
My code is ran in Python 3.8.2, name of file is main.py
"def convert_docx_file(filename):
    path = os.path.dirname(os.path.realpath('__file__'))
    path = os.path.join(path, "upload")
    path = os.path.join(path, "thainq")
    path = os.path.join(path, filename)
    print(path)
    html = ''
    with open(path, "rb") as docx_file:
        result = mammoth.convert_to_html(docx_file)
        html = result.value
        messages = result.messages
    print(html)
print(convert_docx_file("Test.docx"))"

After I run python main.py, i receive the error like this:
"$ python convertDocx.py
C:\Users\84165\Desktop\KLTN-backend\upload\thainq\Test.docx
Traceback (most recent call last):
  File "convertDocx.py", line 65, in <module>
    print(convert_docx_file("Test.docx"))
  File "convertDocx.py", line 59, in convert_docx_file
    result = mammoth.convert_to_html(docx_file)
  File "C:\Python38\lib\site-packages\mammoth\__init__.py", line 12, in convert_
    return convert(*args, output_format="html", **kwargs)
  File "C:\Python38\lib\site-packages\mammoth\__init__.py", line 25, in convert
    kwargs["embedded_style_map"] = read_style_map(fileobj)
  File "C:\Python38\lib\site-packages\mammoth\docx\style_map.py", line 66, in re
    with open_zip(fileobj, "r") as zip_file:
  File "C:\Python38\lib\site-packages\mammoth\zips.py", line 9, in open_zip
    return _Zip(ZipFile(fileobj, mode))
  File "C:\Python38\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Python38\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file"

My path to file is : C:\Users\84165\Desktop\KLTN-backend\upload\thainq\Test.docx
I have searched in stackoverflow for hours about this error, but there is no solution.
Am i wrong in somewhere? Thank you in advance.

**Comment by mwilliamson** [comment]
It sounds like the file you're using isn't supported by Mammoth: Mammoth expects the files to be normal docx files, which are zip files.

**Comment by thainquet** [comment]
> It sounds like the file you're using isn't supported by Mammoth: Mammoth expects the files to be normal docx files, which are zip files.

Thank you for quick reply. I have checked the input file and it seems to be a blank file with no content.
I change to use another word file with standard content and mammoth work perfectly.
