### ISSUE TITLE
Is there a plan for table style implementation?

### ISSUE THREAD

**Issue by iruletheworld** [mwilliamson/python-mammoth#91]
Hi, this is a really great package. I am just wondering if there is any plan to enhance table conversion? I just need the borders to show. 

I currently use the trick of 'past as picture' in Word to kinda work around the no border issue. It works ok but the text can be blury and the size of the text in the table often doesn't match the main body.

**Comment by mwilliamson** [comment]
Mammoth is unlikely to support manually applied borders, but could map table styles in the same way as paragraph or run styles. Do you have a minimal example document?

**Comment by mwilliamson** [comment]
I'd apparently forgotten that table styles are already supported, so using table styles in Word, and then mapping those styles to appropriate CSS classes are the best bet.
