### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Natalie15** [mwilliamson/python-mammoth#96]
I install mammoth per instructions (pip install mammoth), then use the instructions per instructions (mammoth input.docx output.docx), specifically
mammoth C\Users\Natalie\Documents\theDocument.docx theDocument.html

I get this error: IOError: [Erno 2] No such file or directory: 'C\\Users\\Natalie\\Documents\\theDocument.docx'

I did doublecheck to see if I mistype the path, and I definitely only used one \ and not two.  Any advice?

**Comment by ulfgj** [comment]
did you try `C:\` with a colon?

**Comment by Natalie15** [comment]
... No, I sure didn't.  Thanks!  Quick question:  where is the html file placed when the command runs?  Now it runs with no errors, but nothing seems to happen either.

**Comment by mwilliamson** [comment]
The file should be written to your second argument i.e. `theDocument.html`.

**Comment by Natalie15** [comment]
Right, but does it create that document itself or does the user have to create a blank document named theDocument.html?  If it creates itself, where does it instantiate, as it's not showing up in the same folder as the .docx file.

**Comment by mwilliamson** [comment]
It'll create the file if it doesn't already exist. The path will be relative to wherever you're running the command from. So, for instance, if the working directory that you're running the command from is `C:\Users\Natalie\Documents`, then the output will be in `C:\Users\Natalie\Documents\theDocument.html`.

**Comment by Natalie15** [comment]
Thanks!
