### ISSUE TITLE
all-caps style-mapping rule not understood

### ISSUE THREAD

**Issue by valentinoli** [mwilliamson/python-mammoth#98]
Hello

I tried using the following rule in my style-map but mammoth would not parse it.
```
all-caps => span.b-uppercase
```

I expect explicitly applied uppercasing to be mapped as 
```html
<span class="b-uppercase">{text}</span>
```

I received the following warning message:
```
Did not understand this style mapping, so ignored it: all-caps => span.b-uppercase
```

mammoth version: 1.4.12
Python version: 3.9.1
OS: Windows 10

**Comment by mwilliamson** [comment]
Hmm, that's strange. Could you upload thethe style map file you're using?

**Comment by valentinoli** [comment]
Thanks for the prompt response!
Here it is (the first part of it):
```txt
# Inline mappings
i => span.b-italic
b => span.b-bold
u => span.b-underline
small-caps => span.b-smallcaps
all-caps => span.b-uppercase

# Ignored generic styles
p[style-name='Normal'] => !
p[style-name='Heading 1'] => !
p[style-name='Heading 2'] => !
p[style-name='Heading 3'] => !
p[style-name='Heading 4'] => !
p[style-name='Heading 5'] => !
p[style-name='Heading 6'] => !
```

**Comment by mwilliamson** [comment]
Could you upload the file, rather than copying and pasting it, to make sure that I've got the file exactly as you do?

**Comment by valentinoli** [comment]
[style-map.txt](https://github.com/mwilliamson/python-mammoth/files/6024702/style-map.txt)

**Comment by mwilliamson** [comment]
Ah, I should have paid attention to your original description: you're using a version of Mammoth before support was added for `all-caps`.

**Comment by valentinoli** [comment]
Ahhh, that's it! Thank you :)
